# This is a basic workflow to help you get started with Actions

name: e2e browser tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: Run a one-line script
        run: npm install
     
      - name: Run a multi-line script
        run: npm run compile
        
      - name: Run a multi-line script
        run: npm run test:full-headless
